axon:
  axonserver:
    componentName: product-catalog-write

kumuluzee:
  xa-datasources:
    - jndi-name: jdbc/PostgresXADS
      connection-url: jdbc:postgresql://localhost:5432/productCatalog
      xa-datasource-class: org.postgresql.xa.PGXADataSource
      #connection-url: jdbc:postgresql://pc:5432/productCatalog
      username: postgres
      password: postgres
      pool:
        max-size: 2000