version: '3'
services:
  pc-write:
    image: "matijaklj/pc-write:latest"
    container_name: "pc-write"
    ports:
      - "8080:8080"
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65000
    environment:
      - KUMULUZEE_XA-DATASOURCES[0]_CONNECTION-URL=jdbc:postgresql://localhost:5432/productCatalog
      - KUMULUZEE_XA-DATASOURCES[0]_POOL_MAX-SIZE:10000
      - KUMULUZEE_XA-DATASOURCES[0]_USERNAME=postgres
      - KUMULUZEE_XA-DATASOURCES[0]_PASSWORD=postgres
      - AXON_AXONSERVER_SERVERS=10.132.0.19