axon:
  axonserver:
    componentName: product-catalog-read
    #servers: axon-server
 # eventhandling:
    #processors:
    #  products:
    #    mode: subscribing
    #    threadCount: 2
    #    initialSegmentCount: 4
    #  categories:
    #    mode: tracking
    #    threadCount: 2
    #    initialSegmentCount: 4

kumuluzee:
  mongodb:
    connection-string: "mongodb://localhost"
    #connection: "mongodb://mongo-db"
  datasources:
    - jndi-name: jdbc/pcReadDS
      #connection-url: jdbc:postgresql://postgres-db:5432/productCatalog
      connection-url: jdbc:postgresql://localhost:5432/productCatalog
      username: postgres
      password: postgres
      pool:
        max-size: 2000